version: '3.8'

services:

  mongodb_agenda:
    image: mongo
    container_name: mongodb_agenda
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: datapolicy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo_express_agenda:
    image: mongo-express
    container_name: mongo_express_agenda
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user  
      ME_CONFIG_MONGODB_ADMINPASSWORD: datapolicy 
      ME_CONFIG_MONGODB_SERVER: mongodb_agenda 
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
    depends_on:
      - mongodb_agenda

  scraper_agenda:
    build: .
    container_name: scraper_agenda
    restart: always
    depends_on:
      - mongodb_agenda
    volumes:
      - .:/app

volumes:
  mongodb_data:

